### ISSUE TITLE
blazorContextMenu.min.css returns a 404 error after updating to version 1.11.0

### ISSUE THREAD

**Issue by dantronik-markus** [stavroskasidis/BlazorContextMenu#106]
**Describe the bug**
After updating to 1.11.0 I keep getting a 404 error when loading BlazorContextMenu 1.11.0.

**To Reproduce**
Update BlazorContextMenu to version 1.11.0

**Expected behavior**
Update should work as expected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 1.11.0

Failed to load resource: the server responded with a status of 404 ()

Downgrading to the previous version and reloading the site, bypassing the cache fixes it.

**Comment by stavroskasidis** [comment]
Wow, something must have gone wrong in the packaging process.
Thank you I will look into it.

**Comment by stavroskasidis** [comment]
Btw, you can reference the non-minified version temporarily until I fix this.
"blazorContextMenu.css"

**Comment by stavroskasidis** [comment]
Fixed in 1.11.1
