### ISSUE TITLE
Error when className is not of type string

### ISSUE THREAD

**Issue by SebastianWachsmuth** [stavroskasidis/BlazorContextMenu#114]
For some DOM-Elements className is not of type string (svg for example)

In those cases .split() will throw. same error as #110

could maybe be fixed by using [element.classList](https://www.w3schools.com/jsref/prop_element_classlist.asp). it has a contains method

**Comment by stavroskasidis** [comment]
Ok thank you for reporting this. I will work on it and provide a patch.

**Comment by SebastianWachsmuth** [comment]
the simplest way, with the fewest changes is to replace line 41 and 63 with 
`var classes = el.classList != undefined ? el.classList : [];`

**Comment by stavroskasidis** [comment]
Changed in 1.13
