### ISSUE TITLE
"Cannot read properties of undefined (reading 'removeEventListener')" after closing menu

### ISSUE THREAD

**Issue by dantronik-bugreporting** [stavroskasidis/BlazorContextMenu#124]
**Describe the bug**
A second after closing the menu, I'm getting this error in the JS console:
```
blazorContextMenu.js:256 Uncaught TypeError: Cannot read properties of undefined (reading 'removeEventListener')
    at HTMLLIElement.closeSubMenus (blazorContextMenu.js:256:31)
closeSubMenus @ blazorContextMenu.js:256
```

**To Reproduce**
1. Click submenu item (which opens a window and closes the current context menu
2.  Error in the JS console.

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 102.0.5005.62

**Comment by stavroskasidis** [comment]
Thank you for reporting this. I cannot reproduce it locally. Could you be so kind as to provide a project tha reproduces the bug ?

**Comment by dantronik-bugreporting** [comment]
I've tried to reproduce the issue again, but somehow can't. Maybe the issue got fixed by the latest version or it was a cache issue. Anyway, closing this.
