### ISSUE TITLE
Support Touch and Mobile

### ISSUE THREAD

**Issue by vertonghenb** [stavroskasidis/BlazorContextMenu#14]
Wondering if there are plans to support mobile browsers.
For example using Google Chrome or Firefox on iOS.

Maybe events like: 
double tap/ long tap?

**Comment by stavroskasidis** [comment]
Actually long tap is working (tested on my android).

**Comment by stavroskasidis** [comment]
I am closing this because with the latest version you can perform all of these in mobile
LeftClick -> Tap
RightClick -> Long Tap
DoubleClick -> Double Tap

**Comment by jzabroski** [comment]
@stavroskasidis maybe update readme?
