### ISSUE TITLE
About running speed

### ISSUE THREAD

**Issue by WhyILoveSpringRoll** [stavroskasidis/BlazorContextMenu#149]
I have used this component for each cell in a table, approximately 30 columns and 15 rows. However, the response speed after right-clicking is slower when compared to fewer cells. How can I improve performance? Thank you very much.

**Comment by WhyILoveSpringRoll** [comment]
After clicking the item, it takes about 1.9 seconds to close menu

**Comment by stavroskasidis** [comment]
Can you provide a code sample ?

**Comment by WhyILoveSpringRoll** [comment]
> Can you provide a code sample ?

maybe its my ui's problem,I'll try more.thank you so much

**Comment by WhyILoveSpringRoll** [comment]
I was experiencing a slowdown using a UI component, but after rewriting the table component, the speed has significantly improved

**Comment by XTR-KyleWilkins** [comment]
@WhyILoveSpringRoll What did you end up changing to get it to work? I have about the same issue but its on every row and there are hundreds of rows.
