### ISSUE TITLE
TypeError when hovering over submenu items in BlazorContextMenu

### ISSUE THREAD

**Issue by adrien426** [stavroskasidis/BlazorContextMenu#155]
**Describe the bug**
I encountered a JavaScript error in the BlazorContextMenu component while using Blazor Server. The error appears when hovering over submenu items, with the message: 'TypeError: Cannot read properties of undefined (reading 'removeEventListener'). 

**Screenshots**
![image](https://github.com/stavroskasidis/BlazorContextMenu/assets/9755757/1ef9689b-7071-4dae-ae6a-ea4c11ea8772)

**Comment by stavroskasidis** [comment]
Merged the fix.

**Comment by stavroskasidis** [comment]
Version 2.1 contains the fix. Thank you
