### ISSUE TITLE
upgrade to blazor 0.8

### ISSUE THREAD

**Issue by julienGrd** [stavroskasidis/BlazorContextMenu#27]
Hi stavroskasidis, thanks for your work on this project !
I actually need your component but i begin with the last version of blazor (0.8, including .net core 3 preview).

It's possible to upgrade your project to upgrade on this ? i already did on my computer, it's work perfectly, so if you want i can commit on your project to target to blazor 0.8/.NET CORE 3

Thanks !

Julien

**Comment by stavroskasidis** [comment]
I have a branch already migrated. I haven't merged it yet because razor components are not yet working with Blazor libraries. I will probably go ahead and release though

**Comment by julienGrd** [comment]
OK I follow this ! thanks !

**Comment by stavroskasidis** [comment]
I have released a beta that is migrated to blazor 0.8.0.
You can find it here
https://www.nuget.org/packages/Blazor.ContextMenu/0.11.0-beta-280

I will refrain from releasing a non-beta until the razor components problem is fixed (you wouldn't be able to use the library with Razor Components anyway). If you just want to use with blazor 0.8 then use the 11-beta.

**Comment by julienGrd** [comment]
OK thanks ! for the razor component i don't know, i focus on the client side for the moment, wich seem works perfectly in 0.8.

**Comment by stavroskasidis** [comment]
Glad to be of help. I will go ahead and close the issue now, since the library is now usable with blazor 0.8
