### ISSUE TITLE
any way to have an event like "Shown" on contextMenu

### ISSUE THREAD

**Issue by julienGrd** [stavroskasidis/BlazorContextMenu#42]
Hi and thanks for your work

It could be nice to Have an event when the contextMenu appear to run some piece of code (in my case, I would like to run some code wich determinate status of my menu, visibility, disabled, etc).

You think it's possible to integrate this on your next version ?

something like that

`<ContextMenu Id="tableContextMenu" OnShown="@OnShown">`

If you don't have time, I think I can integrate this if you want
- 1 parameter of type Action on ContextMenu.razor
 [Parameter]
public Action OnShown { get; protected set; }
- in the internal void Show(string x, string y, string targetId)
this.OnShown?.Invoke();

thanks !

**Comment by stavroskasidis** [comment]
I will implement this, definitely. I was thinking about it myself. It will be in the next version.

**Comment by julienGrd** [comment]
OK perfect ! don't forget to give arguments to have the x, y and targetId on the event ! (it was not in my request but i will need this too)

**Comment by stavroskasidis** [comment]
Sure

**Comment by stavroskasidis** [comment]
Added `OnAppearing` on `ContextMenu` in 0.15. Will be up in nuget in a bit through CI
