### ISSUE TITLE
Allow Associating ContextMenuTrigger with an ID/Tag

### ISSUE THREAD

**Issue by Zigby** [stavroskasidis/BlazorContextMenu#55]
A am adding a ContextMenuTrigger to each table row in a HTML5 table. For each row (ContextMenuTrigger) I would like to provide a tag/id that gets passed to the callback when a menu item is invoked so I know which data item the context menu was invoked for.

I was expecting to be able to do something like this
 @foreach (var item in Items)
        {
            <ContextMenuTrigger **Tag="@item.Id.ToString()"** WrapperTag="tr" MenuId="tableContextMenu" MouseButtonTrigger="MouseButtonTrigger.Right">
                
and then be able to get the Tag value in the ItemClick handler
void OnClick(BlazorContextMenu.ItemClickEventArgs e)
  {
     string ItemId = e.ContextMenuTrigger.Tag;

or similar....

**Comment by stavroskasidis** [comment]
This is definitely something that I want to implement and is on the "todo" list. Until it is implemented you could use the **e.ContextMenuTargetId** and javascript interop to discover the "row" clicked.

You can find sample code on how to do this here:

https://blazor-context-menu-demo.azurewebsites.net/gridsample

**Comment by stavroskasidis** [comment]
I am planning to add this feature in 0.20. Working on it currently.

**Comment by stavroskasidis** [comment]
This feature is now implemented in [0.20](https://www.nuget.org/packages/Blazor.ContextMenu/0.20.0).

Check the sample again to see how to use:
https://blazor-context-menu-demo.azurewebsites.net/gridsample

**Comment by Zigby** [comment]
This is the fastast Response that I have ever experienced. Thanks a lot I Will try it out tomorrow!
