### ISSUE TITLE
Show/Hide the context menu from code

### ISSUE THREAD

**Issue by YBAZAN** [stavroskasidis/BlazorContextMenu#63]
Hi,

I really love your component. So powerful!

I would need to show/hide a contextual menu from the code. I have the coordinates (X,Y) to position the menu dynamically.

Do you think it would be simple to implement in your component?

**Comment by stavroskasidis** [comment]
Thank you. Yes it could be possible, but some changes are probably required. I will investigate the possibility when I have some free timw

**Comment by jzabroski** [comment]
My first thought upon reading this is it would be nice to have Tether.js-like component apart from the Context Menu itself.  Tether.js is a library built by Twitter for tethering components to DOM elements (or other components).  In using npmTrends, it seems Popper.js is way more popular - not sure why? https://www.npmtrends.com/popper.js-vs-tether

**Comment by jzabroski** [comment]
Ah, the reason Popper.js is more popular than Tether.js is because Bootstrap v4 swapped out Tether.js for Popper.js.  Sorry, I have not done much Web dev the last 3 years.  The last time I did web dev, it was with Bootstrap v4 alpha 4.

**Comment by stavroskasidis** [comment]
@YBAZAN Implemented in version 1.1

You can see a sample here:
https://blazor-context-menu-demo.azurewebsites.net/showhidebycode

**Comment by YBAZAN** [comment]
Thank you so much!
The solution is elegant. 

You made my day!
