### ISSUE TITLE
[Regression] OnAppearing is sometimes with ContextMenuTargetId null

### ISSUE THREAD

**Issue by julienGrd** [stavroskasidis/BlazorContextMenu#65]
Hi and thanks for your work !
I have a problem with your library since last versions (i don't know exactly wich one).
I use your library with table and use the "old" system, retrieve a ContextMenuTargetId  and then i retrieve my element by myself in js.
I can't use the new version where you pass data because i need have the hand on the <tr> generated, so i kept the global trigger which include the table.

Now, depend where i click on the table, but sometimes i have ContextMenuTargetId  null (which for me was normally impossible). So i can't retrieve my item.

It seem the first time i click on an element, it's OK, but then if i reclick on this element, the ContextMenuTargetId  become null

Do you have an explanation for that ?

You will find a repro here : https://github.com/julienGrd/BlazorAppReproBugContextMenu
- go to the fetch data
- right click on the first row / first cell => normally is OK, menu is shown
- reclick on the first row / first cell => the menu not show, if you debug the OnAppearing you will see the value null.

Good luck !

**Comment by stavroskasidis** [comment]
Thank you for the repro project. I will check it out asap.

**Comment by stavroskasidis** [comment]
Fixed in 1.2
