### ISSUE TITLE
IsShown Member

### ISSUE THREAD

**Issue by Hinne123** [stavroskasidis/BlazorContextMenu#68]
First of all: Thanks for your awesome work!

At the moment i am using your context menu on a table cell. Further more i use a tooltip for every cell. My problem is that the tooltip, when activated, sets itself in front of everything else. So i can't use your context menu for cells which also have a tooltip.

The easiest solution for me would be to deactivated the tooltip when activating the context menu. But i think there is no such member or event which i could use for that. 

I saw the onAppearing Event, and i think i could have used that one, but then i could never comfortably activate the tooltip again.

You may have an idea how to solve my problem. Otherwise i think a good solution would be a member which tells me about the context menu status, or a onHiding event.

For some reason i cannot compile the project, otherwise i would solved this problem by myself. Sorry for that!

**Comment by stavroskasidis** [comment]
I think an "OnHiding" event is required. I will work on it asap.
Thank you

**Comment by stavroskasidis** [comment]
Implemented `OnHiding` event in 1.3

PR #69
