### ISSUE TITLE
Support for stopPropagation

### ISSUE THREAD

**Issue by julienGrd** [stavroskasidis/BlazorContextMenu#71]
Hello and thanks for your library, it is very useful for my project !

Sometimes, inside a container which react to a contextMenu, I need tu put some child component which also react to contextMenu (not yours, the classic html contextmenu)
In this case, i wan't to "cancel" the appearing of yours contextMenu and let my code make something else.

I was thinking with the new stopPropagation in the .net core 3.1.0 it will be OK (https://docs.microsoft.com/fr-fr/aspnet/core/blazor/components?view=aspnetcore-3.1#stop-event-propagation), but its not.

How to reproduce :
- first of all, upgrade the projects of your solution in .net core 3.1.0 and .net standard 2.1 and  with the latest nugget 
- put this piece of code somewhere in a page
````
@inject IJSRuntime JsRuntime
<ContextMenuTrigger MenuId="menuTestPropagation">
    <div style="width:400px; height:400px; background-color: blue">
        <div style="width:200px; height:200px; margin: auto; background-color: red" @oncontextmenu="ChildrenClick" @oncontextmenu:stopPropagation="true">
            @**@
        </div>
    </div>
</ContextMenuTrigger>
<ContextMenu Id="menuTestPropagation">
    <Item Id="menuTestPropagation-item1">Item 1</Item>
    <Item Id="menuTestPropagation-item2">Item 2</Item>
</ContextMenu>

protected async Task ChildrenClick()
    {
        await this.JsRuntime.InvokeVoidAsync("alert", "children was clicked");
    }
````

launch the app, if you right click on the children red square, you have the ChildrenClick called (which is OK), but also the menu appaering (which is not OK, I wan't the directive @oncontextmenu:stopPropagation="true" prevent your menu appearing)

Do you think you have time to check that ?

If needed, i can submit a PR with the upgrade of your project in .net core 3.1 + .net standard 2.1 and solve this case if you know approximatively how to solve it.

Thanks !

Julien

**Comment by stavroskasidis** [comment]
Thanks for the code tha reproduces the behaviour. I will have to look into it to figure out what is going on. It should work out of the box

**Comment by stavroskasidis** [comment]
After some investigation, it seems that this is a **Blazor** bug. It should be working by default. 

I can however provide you with some workarounds:

**Workaround 1**
You could use the `OnAppearing` event to prevent showing the menu depending on the target clicked. E.g:
 
```xml
@inject IJSRuntime JsRuntime
<ContextMenuTrigger MenuId="menuTestPropagation">
    <div style="width:400px; height:400px; background-color: blue">
        <div id="redbox" 
                 style="width:200px; height:200px; margin: auto; background-color: red" 
                 @oncontextmenu="ChildrenClick">
        </div>
    </div>
</ContextMenuTrigger>
<ContextMenu Id="menuTestPropagation" OnAppearing="OnAppearing">
    <Item Id="menuTestPropagation-item1">Item 1</Item>
    <Item Id="menuTestPropagation-item2">Item 2</Item>
</ContextMenu>

@code{
    protected async Task OnAppearing(MenuAppearingEventArgs e)
    {
        if(e.ContextMenuTargetId == "redbox")
        {
            e.PreventShow = true;
        }
    }

    protected async Task ChildrenClick()
    {
        await this.JsRuntime.InvokeVoidAsync("alert", "children was clicked");
    }
}
```

**Workaround 2**
You could use the javascript-side event to prevent it from bubbling. E.g:

```xml
<ContextMenuTrigger MenuId="menuTestPropagation">
    <div style="width:400px; height:400px; background-color: blue">
        <div style="width:200px; height:200px; margin: auto; background-color: red" 
                oncontextmenu="event.stopPropagation(); event.preventDefault();">
        </div>
    </div>
</ContextMenuTrigger>
<ContextMenu Id="menuTestPropagation">
    <Item Id="menuTestPropagation-item1">Item 1</Item>
    <Item Id="menuTestPropagation-item2">Item 2</Item>
</ContextMenu>
```
The only "downside" for this approach is that if you want to also run c# code in the `oncontextmenu` event, you will have to use js interop.

Also please consider opening an issue in the aspnet core repository so that they can investigate this.
I hope I helped you.

**Comment by julienGrd** [comment]
Thanks for your response ! at least i have a workaround ! But its true it can be nice to works natively.
Can you provide me some elements to open a tickets on the .net core repository (whats' wrong, reproducing example, kind of stuff)

Thanks !

**Comment by stavroskasidis** [comment]
Certainly

It seems that it has something to do with combining js events with c# events.
Here are two code samples, one that works (only C# events) and one that doesn't (js plus c# event)

**Sample 1 - Using only C# events (this works)**
```xml
@inject IJSRuntime JsRuntime
<div>
    <div style="width:400px; height:400px; background-color: blue" 
             @oncontextmenu="ParentClick">
        <div style="width:200px; height:200px; margin: auto; background-color: red" 
                       @oncontextmenu="ChildrenClick" 
                       @oncontextmenu:stopPropagation @oncontextmenu:preventDefault>
        </div>
    </div>
</div>

@code{
    protected async Task ChildrenClick()
    {
        await this.JsRuntime.InvokeVoidAsync("alert", "children was clicked");
    }

    protected async Task ParentClick()
    {
        //this is not called. Working correctly
        await this.JsRuntime.InvokeVoidAsync("alert", "parent was clicked");
    }
}
```

**Sample 2 - Using a js event on parent but C# on child (this DOESNT work)**
```xml
@inject IJSRuntime JsRuntime
<div>
    <div style="width:400px; height:400px; background-color: blue" 
              oncontextmenu="alert('parent was clicked');">
        <div style="width:200px; height:200px; margin: auto; background-color: red" 
             @oncontextmenu="ChildrenClick" 
             @oncontextmenu:stopPropagation @oncontextmenu:preventDefault>
        </div>
    </div>
</div>

@code{
    protected async Task ChildrenClick()
    {
        await this.JsRuntime.InvokeVoidAsync("alert", "children was clicked");
    }
}
```

If you open an issue would you also post it in this one? Thanks

**Comment by julienGrd** [comment]
sure its done (https://github.com/aspnet/AspNetCore/issues/17657) ! thanks for your investigation !

**Comment by stavroskasidis** [comment]
closing as external
