### ISSUE TITLE
right click twice to show context menu make the contexte menu unable to disappear

### ISSUE THREAD

**Issue by julienGrd** [stavroskasidis/BlazorContextMenu#72]
**Describe the bug**
if you right click twice for trigger a context menu, the context menu which appear cannot be closed by left-click outside

**To Reproduce**
- right click on a context menu trigger, the context menu appear, left click outside, it disappear => OK
- right click on a context menu trigger, the context menu appear, right click again, the context menu show again, left click outside, nothing happened. to hide them, you have to right click again and then left click outside

thanks !

Julien

**Comment by stavroskasidis** [comment]
Thank you for the reproduce instructions. I will look into it

**Comment by stavroskasidis** [comment]
Fixed in 1.4
