### ISSUE TITLE
Change Enabled property based on Data attribute 

### ISSUE THREAD

**Issue by tobbi** [stavroskasidis/BlazorContextMenu#78]
**Is your feature request related to a problem? Please describe.**
I want to toggle the Enabled property based on the currently selected item's Data attribute, so I can enable the item when a certain condition is true.
```xml
 <Item OnClick="@Synchronize" Enabled="@CanSynchronize(CurrentNode)">Synchronize</Item>
```

**Describe the solution you'd like**
It would be great if the Enabled property of a ContextMenuItem could be bound to an event handler that gets a similar structure to `ItemClickEventArgs`so I can get the current item's data attribute.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tobbi** [comment]
I managed to get the item under the cursor using the `OnAppearing` handler on the context menu. I'm not sure if this is still a valid bug report considering I found a workaround.

**Comment by stavroskasidis** [comment]
You found the way to do it, not a workaround :).

You can also use **@context.Data** to access the data currently passed to the context menu.
So you can do something like
```
<Item OnClick="@Synchronize" 
Enabled="@((context.Data as MyDataType).CanSynchronize)">Synchronize</Item>
```
