### ISSUE TITLE
Can this be used in a Razor Class Library?

### ISSUE THREAD

**Issue by charleskessler** [stavroskasidis/BlazorContextMenu#79]
Hello -- excellent work on this component, very excited to integrate it with my application.

One problem I'm having is I'm not able to import the component into a Razor Class Library project. 
I'm fairly green to Blazor, so it's likely not a bug but me misunderstanding something.

1. Install NuGet package
2. Try to add @using BlazorContextMenu to _Imports.razor,
![image](https://user-images.githubusercontent.com/6663095/79355321-7c008c80-7f0b-11ea-941b-7949b9cd6501.png)

I've been able to use it within a Blazor App project, but I'd like to be able to include it in a separate Razor Class Library for reuse.

Thanks for your effort, and help!

**Comment by stavroskasidis** [comment]
Sure it should be usable. Make sure the razor class library is **netstandard2.1**. Here is a  csproj that works

```
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Blazor.ContextMenu" Version="1.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="3.1.0" />
  </ItemGroup>

</Project>
```

**Comment by charleskessler** [comment]
Ah! Glad it is something so simple. Usually NuGet would warn me of a dependency versioning mismatch, alas..

Thanks very much for the quick response!

**Comment by stavroskasidis** [comment]
Cheers !
