### ISSUE TITLE
component stop working after 1.7 upgarde

### ISSUE THREAD

**Issue by julienGrd** [stavroskasidis/BlazorContextMenu#83]
Hello, and thanks again for your component, it is very usefull for my app.

However, since i upgrade to 1.7, it completely stop working. 

Whats happen is on my grid I listen the onContextMenu on the <tr> and i programmaticaly launch the contextMenu with _blazorContextMenuService. With 1.7 version, this event is never launch.

so for make it work, i have to select my row with left click and then make a right click to have the menu appaering.

I try to understand whats happen, Nothing sure but the stopPropagation you included in Item.razor and/or in the js seem cause this.  (its strange beacuse normally it's not related, but it seem the best explication)

Do you think you can expose this behavior with an option ? like a boolean stopPropagation ?

thanks !

**Comment by stavroskasidis** [comment]
Thank you for reporting this. I will investigate. In the meanwhile please use version 1.6, since 1.7 only has that change

**Comment by stavroskasidis** [comment]
I cannot seem to reproduce the bug. The IBlazorContextMenuService seems to work properly.

Can you please provide some sample code or a sample project that reproduces the bug?
Also can you please make sure that 1.6 works for you and that **only** 1.7 breaks your functionallity ?

**Comment by julienGrd** [comment]
The problem don't come from IBlazorContextMenuService  but from my event "oncontextmenu" on my table row which is not fire since 1.7 version.

yes it's a 1.7 behavior, for now i stay in 1.6 and everything works perfectly.

I will see to make you a repro project but i don't really have the time for now so it will make certainly few days.

for no, it works inn 1.6 so nothing hurry on my side

**Comment by julienGrd** [comment]
OK i begin to understand whats happen
first, this happen ONLY on serverside project 
to reproduce the "bug" :
- put on contextmenutrigger around a table
- add an event @oncontextmenu on the tr of the table
- put a breakpoint inside the event fired by the oncontextmenu => you will never reached it

````
<ContextMenuTrigger MenuId="@contextMenuId">
        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Temp. (C)</th>
                    <th>Temp. (F)</th>
                    <th>Summary</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var forecast in forecasts)
                {
                    <tr @oncontextmenu="@((args) => OnContextMenu(args))">
                        <td>@forecast.Date.ToShortDateString()</td>
                        <td>@forecast.TemperatureC</td>
                        <td>@forecast.TemperatureF</td>
                        <td>@forecast.Summary</td>
                    </tr>
                }
            </tbody>
        </table>
    </ContextMenuTrigger>
    <ContextMenu Id="@contextMenuId">
        <Item OnClick="@OnClick">Item 1</Item>
        <Item OnClick="@OnClick">Item 2</Item>
        <Item OnClick="@OnClick" Enabled="false">Item 3 (disabled)</Item>
        <Seperator />
        <Item>
            Submenu
            <SubMenu>
                <Item OnClick="@OnClick">Submenu Item 1</Item>
                <Item OnClick="@OnClick">Submenu Item 2</Item>
            </SubMenu>
        </Item>
    </ContextMenu>

@code {
    private WeatherForecast[] forecasts;

    private string contextMenuId = "MycontextMenuId";

    protected override async Task OnInitializedAsync()
    {
        forecasts = await ForecastService.GetForecastAsync(DateTime.Now);
    }

    protected void OnContextMenu(MouseEventArgs args)//never reached
    {
        Console.WriteLine("row oncontextmenu fired");
        //_blazorContextMenuService.ShowMenu(contextMenuId, (int)args.ClientX, (int)args.ClientY);

        //this.LaunchStateHasChanged();
    }

    void OnClick(ItemClickEventArgs e)
    {
        Console.WriteLine($"Item Clicked => Menu: {e.ContextMenuId}, MenuTarget: {e.ContextMenuTargetId}, IsCanceled: {e.IsCanceled}, MenuItem: {e.MenuItemElement}, MouseEvent: {e.MouseEvent}");
    }
}
````

I have a sample project ready to commit if you are not able to reproduce

good luck !
PS : on my side the contextmenutrigger was redondant because i launch the contextMenu by the service, so remove contextmenutrigger solved my problem. But we can imagine using contextmenu for totally other things, so it need to be solved.

**Comment by stavroskasidis** [comment]
Thank you for taking the time to write that code. I will look into it ASAP and come back to you. I am also considering exposing the stopPropagation as a parameter to be able to turn it off.

**Comment by stavroskasidis** [comment]
I am preparing version 1.8, where stop propagating will be a parameter on the `ContextMenuTrigger`

**Comment by stavroskasidis** [comment]
Created version 1.8, `StopPropagation` is now a parameter on `ContextMenuTrigger`.

**Comment by julienGrd** [comment]
@stavroskasidis thanks for your reactivity and your work on this project, it is really helpfull for my project
