### ISSUE TITLE
Long context menu items can overlap the fixed-width (200px) context menu

### ISSUE THREAD

**Issue by dantronik-markus** [stavroskasidis/BlazorContextMenu#85]
**Is your feature request related to a problem? Please describe.**
When the text contained in a menu item exceeds a certain number of characters, the text gets drawn above the 200px width menu item. Changing the width to something bigger than 200px using CSS works, however, then the position for the submenus is not correct.

**Describe the solution you'd like**
BlazorContextMenu should automatically adjust the width to the content of the menu item. Alternatively, it should allow for a width setting on the `BlazorContextMenu` tag in the razor file.

**Comment by stavroskasidis** [comment]
Thank you for reporting this. I will look into it

**Comment by stavroskasidis** [comment]
I cannot seem to reproduce the behavior you are describing


![image](https://user-images.githubusercontent.com/12549761/94451339-edc94b80-01b6-11eb-81fd-3f35fb179342.png)




Could you provide some more info or, even better, a code sample that reproduces this behavior ?

**Comment by dantronik-markus** [comment]
You're totally right. The fixed width was due to a custom CSS rule I had applied. I don't know how I could be so oblivious to not notice that before. Sorry about that.

**Comment by stavroskasidis** [comment]
No worries, we all make mistakes. Thank you for using my component
