### ISSUE TITLE
Feature: Programatically open context menu without ContextMenuTrigger

### ISSUE THREAD

**Issue by Liero** [stavroskasidis/BlazorContextMenu#92]
**Is your feature request related to a problem? Please describe.**
I need to manually handle right click event, resp. @OnContextMenu, in order to get some other details.

Particularly in my case I have a data grid component that handles @OnContextMenu for me:

```csharp
protected virtual async Task OnContextMenuHandler(RowMouseEventArgs<TRow> args)
{
    MouseEventArgs mouseArgs = args.EventArgs
    var clickedCell = _grid.GetCell(args);
    //how to show  ContextMenu with clickedCell as Data parameter?
}
```

**Describe the solution you'd like**
  I would love to see more decoupling from ContextMenuTrigger and ability to show ContextMenu programatically:

```csharp
await _contexMenu.Show(mouseArgs.ClientX, mouseArgs.ClientY);
```

would you like me to submit PR?

**Comment by stavroskasidis** [comment]
Hello,

The feature you are requesting is already implemented!
Just inject the `IBlazorContextMenuService` and call the `ShowMenu` method

```csharp
@inject IBlazorContextMenuService contextMenuService

protected virtual async Task OnContextMenuHandler(RowMouseEventArgs<TRow> args)
{
    MouseEventArgs mouseArgs = args.EventArgs
    var clickedCell = _grid.GetCell(args);
    await contextMenuService.ShowMenu("myMenuId", mouseArgs.ClientX, mouseArgs.ClientY, clickedCell);
}
```


You can see a live sample here:
https://blazor-context-menu-demo.azurewebsites.net/showhidebycode

**Comment by Liero** [comment]
I'm sorry, my fault. Thanks.

**Comment by Liero** [comment]
On a side note:

```csharp
Task ShowMenu(string id, int x, int y, object data); 
```
should probably be

```csharp
Task ShowMenu(string id, double x, double y, object data);
```

because MouseEventArgs.ClientX/ClientY is also double.

Another side note:

I believe the ContextMenuService is somewhat redundant. With tiny bit of refactoring we could call ContextMenu.ShowMenu(...) instead with following benefits:

  1. No need to register yet another service in Startup.cs
  2. Avoiding magic strings (id), which would make the client code little bit more type safe and refactorable
 
It would still be possible to create my own ContextMenuService if I wanted to.
