### ISSUE TITLE
Item OnClick="@OnClick" is not triggered on a mobile device

### ISSUE THREAD

**Issue by VladislavAntonyuk** [stavroskasidis/BlazorContextMenu#93]
Item OnClick="@OnClick" is not triggered on a mobile device (works fine on desktop)

**Desktop (please complete the following information):**
 - OS: Android 6.0.1
 - Browser Edge

**Comment by stavroskasidis** [comment]
I can't seem to reproduce it on my phone. I need some more info.
1. Are you using Blazor Wasm or Blazor Server?
2. Do the demos in the [demo app](https://blazor-context-menu-demo.azurewebsites.net/) work on your phone ? 
3. Does it work on other mobile browsers, e.g. Chrome ?
