### ISSUE TITLE
Invalid cast exception when used in Child Component

### ISSUE THREAD

**Issue by Liero** [stavroskasidis/BlazorContextMenu#95]
When a context menu is used inside a child component, that is rendered more than once, it is rendered with wrong Data, which might easily lead to runtime exception:

```razor
<Child Item="@("abc")"/>
<Child Item="@(123)"/>
```

child.razor
```razor
@using BlazorContextMenu
@typeparam TItem
<ContextMenu Id="myMenu">
    <Item>Hello</Item>
    @if (((TItem)context.Data) != null)  @*invalid cast exception here*@
    {
        <Item>@context.Data</Item>
    }
</ContextMenu>

<ContextMenuTrigger MenuId="myMenu" Data="Item">
    <p>Right-click on me to show the context menu !!</p>
</ContextMenuTrigger>
```
@code {
    [Parameter]
    public TItem Item {get; set;}
}

**To Reproduce**
1. Go to https://blazorrepl.com/repl/GlYewBvl362TrE7X05
2. Click on 'Run'
3. Right click second paragraph - it works
4. Right click first paragraph  - see error

**Expected behavior**
ContextMenu should not throw exception when correct data is passed

**Comment by stavroskasidis** [comment]
The context menu id must be unique in the DOM. If you want to render a context menu for each child, then each menu must have a different id. Alternatively, you could render the context menu somewhere else (it doesn't matter where it lives, it could live in **App.razor** for all it cares) and then each child only contains the trigger. Then you can pass different data to the menu to differentiate its items.

**Example A:** https://blazorrepl.com/repl/wlkSGWla35chNhov47
```xml
<Child Item="@("abc")"/>
<Child Item="@(123)"/>
```

```xml
@using BlazorContextMenu
@typeparam TItem
@code{
    private string menuId = "menuId_" + Guid.NewGuid().ToString("N");
}
<ContextMenu Id="@menuId">
    <Item>Hello</Item>
    @if (((TItem)context.Data) != null)  @*invalid cast exception here*@
    {
        <Item>@context.Data</Item>
    }
</ContextMenu>

<ContextMenuTrigger MenuId="@menuId" Data="Item">
    <p>Right-click on me to show the context menu !!</p>
</ContextMenuTrigger>
```


**Example B:** https://blazorrepl.com/repl/QPOyGClk38vtNQ6O38
```xml
<Child Item="@("abc")"/>
<Child Item="@(123)"/>

<ContextMenu Id="myMenu">
    <Item>Hello</Item>
    @if (context.Data != default) 
    {
        <Item>@context.Data</Item>
    }
</ContextMenu>

```

Child.razor
```xml
@using BlazorContextMenu
@typeparam TItem
<ContextMenuTrigger MenuId="myMenu" Data="Item">
    <p>Right-click on me to show the context menu !!</p>
</ContextMenuTrigger>
```
